theme: jekyll-theme-hacker

lsi: false
safe: true
source: [sistema-de-gerenciamento-de-floricultura]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
